### ISSUE TITLE
Crash with a no-more-existing file as last used

### ISSUE THREAD

**Issue by dylan666** [michaelknigge/pclparaphernalia#1] opened 2019-03-19 12:00 UTC
I opened a file in "PRN File Analyse" and that file was on a USB Drive.
A removed the drive and tried to open another file but the program crashed before the "Browse" dialog.
I had to remove this reg entry where the last opened file was stored:

HKEY_CURRENT_USER\Software\PCLParaphernalia\Tools\PrnAnalyse\filename

**Comment by michaelknigge** [comment] 2019-03-27 16:20
Thanks for your report. I guess it is not hard to fix, but I'm currently very very busy... But I'll throw an eye on it the next days (if I don't forget)....

**Comment by michaelknigge** [comment] 2019-04-12 22:35
The issue is fixed with commit 1a17284c68f98a86b306f9bd1094a9ef44dd159b. I'll create a new release soon.

**Closed as completed by michaelknigge** 2019-04-12 22:35 UTC
